[package]
name = "contact-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
lettre = "0.10.0-rc.6"
reqwest = "0.11"
openssl = { version = "0.10", features = [ "vendored" ] }
rocket = { version = "0.5.0-rc.2", features = [ "json" ] }
validator = { version = "0.15", features = [ "derive" ] }
