[package]
name = "contact-rs"
version = "0.1.2"
edition = "2021"

[dependencies]
lettre = { version = "0.10.0-rc.7", default-features = false, features = [ "builder", "rustls-tls", "smtp-transport" ] }
reqwest = { version = "0.11", default-features = false, features = [ "json", "rustls-tls" ] }
rocket = { version = "0.5.0-rc.2", features = [ "json" ] }
serde = "1.0.137"
validator = { version = "0.15", features = [ "derive" ] }
