---
name: build
on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 3 * * 0"
  workflow_dispatch:
jobs:
  build_binary:
    name: Build Linux x86_64 binary
    runs-on: ubuntu-latest
    env:
      TARGET: x86_64-unknown-linux-gnu
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
      - name: Cache Cargo registry
        uses: actions/cache@v3
        with:
          key: cargo-registry-${{ runner.os }}
          path: ~/.cargo/registry
      - name: Install Rust stable toolchain
        run: |
          rustup toolchain install --profile=minimal stable
          rustup target install "$TARGET"
      - name: Cargo build
        run: |
          cargo build --jobs "$(nproc)" --locked --release --target "$TARGET"
      - name: Strip binary
        run: |
          strip "target/$TARGET/release/contact-rs"
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: contact-rs_${{ env.TARGET }}
          path: target/${{ env.TARGET }}/release/contact-rs
  build_container:
    name: Build container image
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}
      IMAGE_TAG: latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
      - name: Build container image
        uses: redhat-actions/buildah-build@v2
        with:
          image: ${{ github.event.repository.name }}
          tags: ${{ env.IMAGE_TAG }}
          containerfiles: ./Dockerfile
      - name: Push to ghcr.io
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ github.event.repository.name }}
          tags: ${{ env.IMAGE_TAG }}
          registry: ghcr.io/${{ github.repository_owner }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
