name: build
on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 3 * * 0"
jobs:
  build_binary:
    name: Build Linux x86_64 binary
    runs-on: ubuntu-latest
    env:
      TARGET: x86_64-unknown-linux-gnu
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
      - name: Cache Cargo registry
        uses: actions/cache@v3
        with:
          key: cargo-registry-${{ runner.os }}
          path: ~/.cargo/registry
      - name: Install Rust stable toolchain
        run: |
          rustup toolchain install --profile=minimal stable
          rustup target install "$TARGET"
      - name: Cargo build
        run: |
          cargo build --jobs "$(nproc)" --locked --release --target "$TARGET"
      - name: Strip binary
        run: |
          strip "target/$TARGET/release/contact-rs"
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: contact-rs_${{ env.TARGET }}
          path: target/${{ env.TARGET }}/release/contact-rs
  build_container:
    name: Build container image
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: ${{ github.repository_owner }}/contact-rs
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build image
        run: |
          docker build -t ghcr.io/${{ env.IMAGE_NAME }}:latest .
      - name: Push to GHCR
        run: |
          docker push ghcr.io/${{ env.IMAGE_NAME }}:latest
