---
name: test
on:
  push:
    branches-ignore:
      - main
  pull_request:
  workflow_dispatch:
jobs:
  test_container:
    name: Test container
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
      - name: Build container image
        uses: redhat-actions/buildah-build@v2
        with:
          containerfiles: ./Dockerfile
          image: ${{ github.event.repository.name }}
          tags: test
      - name: Launch container
        run: |
          podman run -d -p 8000:8000 --env-file .env.example "${{ github.event.repository.name }}:test"
      - name: Test web server in container
        run: |
          sleep 5
          curl -Lfv localhost:8000
      - name: Kill container
        run: |
          podman kill -a
