name: Test
on:
  push:
    branches-ignore: main
  pull_request:
jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Rust stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Cargo build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --all-features
      - name: Cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all-features
      - name: Test web server
        run: |
          grep -v '^#' .env.example
          export $(grep -v '^#' .env.example | xargs)
          cargo run &
          sleep 10
          curl -Lf localhost:8000
