name: Test
on:
  push:
    branches-ignore: main
  pull_request:
jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    env:
      TARGET: x86_64-unknown-linux-musl
    steps:
      - uses: actions/checkout@v3
      - name: Install musl-tools
        run: |
          sudo apt-get update
          sudo apt-get install -y musl-tools
      - name: Set up Rust stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          target: ${{ env.TARGET }}
          toolchain: stable
      - name: Cargo build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --all-features --jobs 2 --locked --target ${{ env.TARGET }}
      - name: Cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all-features --jobs 2 --locked --target ${{ env.TARGET }}
      - name: Test web server
        run: |
          grep -v '^#' .env.example
          export $(grep -v '^#' .env.example | xargs)
          target/${{ env.TARGET }}/debug/contact-rs &
          sleep 10
          curl -Lf localhost:8000
          killall contact-rs
      - name: Strip binary
        run: strip target/${{ env.TARGET }}/debug/contact-rs
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: contact-rs_debug_${{ env.TARGET }}
          path: target/${{ env.TARGET }}/debug/contact-rs
  test_container:
    name: Test container image
    runs-on: ubuntu-latest
    env:
      PACKAGE_NAME: contact-rs
    steps:
      - uses: actions/checkout@v3
      - name: Build container
        run: docker build -t $PACKAGE_NAME:test .
      - name: Launch container
        run: docker run -d -p 8000:8000 --env-file .env.example --name ${{ env.PACKAGE_NAME }} ${{ env.PACKAGE_NAME }}:test
      - name: Test web server in container
        run: |
          sleep 5
          curl -Lf localhost:8000
          docker kill ${{ env.PACKAGE_NAME }}
